 #image:
 #file: .gitpod.Dockerfile
 
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    pyenv install 3.6.10  &&
    pyenv local 3.6.10   &&  
    python3 -m pip install numpy==1.17.5 &&
    python3 -m pip install -r requirements.txt &&
    python3 -m pip install -r requirements_fake.txt &&
    python3 -m pip install -e . 

  command: >
    python -c "import mlmodels; print(mlmodels)"


github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    default: true
    
    # enable for all branches in this repo (defaults to false)
    # branches: true
    
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true



    
    
