name:  test_pullrequest

on:
  pull_request:
    branches:
      - dev
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

            
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-venv-mlmodels-${{ hashFiles('**/requirements_fake.txt') }}


    - name: Install numpy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install numpy black
      
    - name: Install repo requirements
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r requirements.txt
        pip install -r requirements_fake.txt


    - name: Install repo
      run: pip install -e . -r requirements.txt   --no-deps


    - name: repo path
      run: python -c "import mlmodels,os ; print(mlmodels); print(os)"


    ########  Test running 
    ##### Please change BELOW to your model name  
    - name: black
      run: black -l 120  --py36 --check --fast  .

    - name: ml_optim
      run: ml_optim

    - name: ml_models
      run: ml_models

    - name: ml_test
      run: ml_test  --do model_tf/1_lstm.py
      
         
